name: pycones19
channels:
  - conda-forge
  - pyviz
dependencies:
  - numpy
  - matplotlib
  - pandas
  - notebook
  - scikit-learn
  - seaborn
  - imageio
  - pillow
  - pip
  - holoviews
  - hvplot
  - panel
  - pip:
    - mglearn
    - streamz
    - umap
